name: Unit Tests (Composer)

on:
  pull_request:
  push:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt

      - name: Run focused unit tests
        run: |
          pytest -q tests/test_strategy_composer_meta.py
