name: Validate Strategies

on:
  pull_request:
  push:
    branches: [ "**" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install validator
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema

      - name: List repository
        run: |
          ls -la

      - name: Validate all strategy JSON files
        shell: bash
        run: |
          set -e
          status=0
          shopt -s nullglob
          files=(strategies/*.json)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No strategy files found; skipping validation."
            exit 0
          fi
          for f in "${files[@]}"; do
            echo "Validating $f"
            python ai_engine/omniverse_strategy_composer.py --validate-file "$f" --meta-validate --strategy-validate --strict || status=1
          done
          exit $status
